//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 宏盈.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COURSE()
        {
            this.BUYBOOK = new HashSet<BUYBOOK>();
            this.TAKE = new HashSet<TAKE>();
        }
    
        public string cID { get; set; }
        public string cname { get; set; }
        public Nullable<System.TimeSpan> ctime { get; set; }
        public string tID { get; set; }
        public string bID { get; set; }
        public string dID { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUYBOOK> BUYBOOK { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual TEACHER TEACHER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAKE> TAKE { get; set; }
    }
}
